//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PropertyDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Listing
    {
        public int ListingID { get; set; }
        public string ListingAddress { get; set; }
        public Nullable<decimal> ListingPrice { get; set; }
        public Nullable<int> NumBedrooms { get; set; }
        public Nullable<bool> IsAvailable { get; set; }
        public Nullable<System.DateTime> DateListed { get; set; }
    }
}
